version: '3'

services:
  kode:
    build: ./kode
    container_name: kode
    volumes:
      - ./data:/var/www/html/Aria2Download:rw
    ports:
      - "8001:80"
    restart: always
  aria2:
    build: ./aria2-ng
    container_name: aria2-ng
    ports:
      - "8000:80"
#      - "443:443"
      - "6800:6800"
    volumes:
      - ./data:/var/www:rw
    environment:
      - DOMAIN=:80
      # - SSL=true
      - RPC_SECRET=0123456789abcdef
      - ARIA2_USER=admin
      - ARIA2_PWD=changeme
      - ENABLE_AUTH=true
    restart: always
